Feature/footer
peaksoft-school/air-bnb-js11 pull request #10
Opened 2024-01-14 11:43 UTC by Matraim

2024-01-14 12:51 UTC, alihanio commented on src/App.jsx
Таза болуш керек 
import './App.css'

const App = () => {
   return <div>Air-bnb</div>
}

export default App
Кантип барса да текшерип буткондон кийин могундай кылып анан жонотосуз

2024-01-14 12:51 UTC, alihanio commented on src/layout/footer/index.js
> +import React from 'react'
React иштетпесениз алып салын

2024-01-15 06:49 UTC, AziatAbd requested changes

2024-01-15 06:49 UTC, AziatAbd commented on src/layout/footer/index.js
Footer.jsx

2024-01-15 06:49 UTC, AziatAbd commented on src/layout/footer/index.js
> +                     <StyleTypography>leave an ad</StyleTypography>
Нужен cursor pointer

2024-01-15 06:50 UTC, AziatAbd commented
все inline стили переделайте с помощью styled

2024-01-15 09:52 UTC, merged