drop-down
peaksoft-school/air-bnb-js11 pull request #17
Opened 2024-01-19 13:28 UTC by alihanio

2024-01-20 07:26 UTC, Matraim approved these changes
LGMT!

2024-01-24 07:56 UTC, AziatAbd requested changes

2024-01-24 07:56 UTC, AziatAbd commented on src/components/UI/DropDown.jsx
не DropDown а Meatballs

2024-01-24 07:56 UTC, AziatAbd commented on src/components/UI/DropDown.jsx
> +            {options?.map((option) => (
в options должен приходить объект с данными типа этого 
![image](https://github.com/peaksoft-school/air-bnb-js11/assets/115453436/d94b746f-7c2a-4eb5-9139-7c438ed9a1d8)

2024-01-24 07:56 UTC, AziatAbd commented on src/components/UI/DropDown.jsx
> +                  selected={option === 'Pyxis'}
что делает selected?

2024-01-24 08:15 UTC, closed without merging