Feature/popularhouse
peaksoft-school/air-bnb-js11 pull request #7
Opened 2024-01-13 13:48 UTC by Matraim

2024-01-14 11:51 UTC, alihanio commented on src/components/@home/PoppularHouseHeadline.jsx
> +import React from 'react'
react колдонбосонуз очуруп сала берин

2024-01-14 11:51 UTC, alihanio commented on src/components/@home/PopularHouse.jsx
> +import React from 'react'
react колдонбосонуз очуруп сала берин

2024-01-14 11:51 UTC, alihanio commented on src/components/@home/PopularHouseCard.jsx
> +import React from 'react'
react колдонбосонуз очуруп сала берин

2024-01-14 11:51 UTC, alihanio commented on src/assets/images/Rectangle 15 (1).jpg
Переименуйте

2024-01-14 11:51 UTC, alihanio commented on src/assets/images/Rectangle 15 (2).jpg
Переименуйте

2024-01-14 11:51 UTC, alihanio commented on src/assets/images/Rectangle 15 (3).jpg
Переименуйте

2024-01-14 11:51 UTC, alihanio commented on src/App.jsx
Буткондон кийин app jsx ти тазалап коюн , башында кандай болсо ошондой кылып коюн

2024-01-15 06:36 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/air-bnb-js11/assets/115453436/78782704-5bbd-4725-9458-36b5e4168970)
обращайте внимание на color

2024-01-15 06:38 UTC, AziatAbd commented
добавьте cursor pointer, они должны быть кликабельны

2024-01-15 06:43 UTC, AziatAbd requested changes

2024-01-15 06:43 UTC, AziatAbd commented on src/App.jsx
> +         <PopularHouse />
очистите app.js

2024-01-15 06:43 UTC, AziatAbd commented on src/components/@home/PopularHouseCard.jsx
> +                  <FullStarIcon /> 3.4
rating тоже приходит с бэка

2024-01-15 06:43 UTC, AziatAbd commented on src/components/@home/PoppularHouseHeadline.jsx
> +            View all
![image](https://github.com/peaksoft-school/air-bnb-js11/assets/115453436/ede2c246-cac3-45cc-8c67-ffca55f6397d)
таким должен быть

2024-01-15 06:45 UTC, AziatAbd commented
все inline стили переделайте используя styled

2024-01-15 09:58 UTC, AziatAbd requested changes

2024-01-15 09:58 UTC, AziatAbd commented on src/components/@home/PoppularHouseHeadline.jsx
src/components/@home

для чего нужна @? Если она не нужна удалите её

2024-01-15 10:26 UTC, merged